### ISSUE TITLE
AppManifest files to launch custom app with appuri 

### ISSUE THREAD

**Issue by bvaibhav1** [microsoft/MixedRealityToolkit-Unreal#16]
Not sure if this is the correct place; posting anyways.

Where do we access the AppManifest file for ue4 to modify hololens appuri extension.

**Comment by luis-valverde-ms** [comment]
I've never done it myself but it seems that you can add information to the manifest via a ```[/Script/HoloLensPlatformEditor.HoloLensTargetSettings]``` section in a .INI file. See for example [HoloLensEngine.ini in UX Tools](https://github.com/microsoft/MixedReality-UXTools-Unreal/blob/6ae6bc6bb7dfa6c7ad4bbdebfeedc39ece1c0f73/UXToolsGame/Config/HoloLens/HoloLensEngine.ini#L3). More details [here](https://github.com/EpicGames/UnrealEngine/blob/46544fa5e0aa9e6740c19b44b0628b72e7bbd5ce/Engine/Source/Programs/UnrealBuildTool/Platform/HoloLens/ManifestGenerator.cs#L58). Let me know how it goes.

**Comment by bvaibhav1** [comment]
Thank you for the quick revert and giving a starting point. I assume i will need to modify the generator to add the desired parameters.

**Comment by bvaibhav1** [comment]
Thank you for this! Worked like a charm. Ended up modifying the manifest generator.
