### ISSUE TITLE
Hololens Packaging: Failure on Publish to Microsoft Store

### ISSUE THREAD

**Issue by bvaibhav1** [microsoft/MixedRealityToolkit-Unreal#18]
Hello,

We are using Source version of UE 4.27.2.

I was able to modify the ManifestGenerator.cs to allow me package an appx bundle for publishing to store.
However the App Certification Kit and on Submitting to store i am getting an error for a missing resource.pri file.

```
The "D:\TRANSFER\a9f1f2d1-c165-ed11-956f-002248798bde\Temp\BE9973\appcert_0FE4\Exxar.Exxar_2.1.11.0_neutral_UnrealAssets_dfbps2k223216\resources.pri" file is missing, and it must be present in the bundle for this resource package.
Manifest Resource Validation Test encountered error: hr = 0x80070002.
```

I am not sure why this error is for a local drive on the system running the validation/app certification kit, and how to resolve this.
Any pointers will be helpful.

Thanks

**Comment by luis-valverde-ms** [comment]
Thanks for reporting this @bvaibhav1 . I'm looking for the right person to follow up. They will post back here with any findings or questions.

**Comment by bvaibhav1** [comment]
Thank you, waiting for a revert (FYR I am on UE 4.27.2) updated on original post as well.

**Comment by fieldsJacksonG** [comment]
On 4.27.2 you can revert this commit (then re-run GenerateProjectFiles.bat) to get WACK to pass now:
https://github.com/EpicGames/UnrealEngine/commit/4af02bdab2e9374508e963fecd7968e01618e9b3

I am investigating a more appropriate fix to generate a working resources.pri file for the neutral appx

**Comment by bvaibhav1** [comment]
Hello Thanks, the Windows Certificate Kit passed the app. Submitted to store as well.
Can you briefly confirm what is the difference created by these changes. This will help us troubleshoot later on for any other issues.
