### ISSUE TITLE
Text To Speech is missing

### ISSUE THREAD

**Issue by nonlin** [microsoft/MixedRealityToolkit-Unreal#5]
Doesn't port over "Text to speech" feature that exist in the holotoolkit. I don't see an example or tutorial how to implement this in this new toolkit. In the previous holotoolkit for Unity for example this existed.

**Comment by luis-valverde-ms** [comment]
Hi @nonlin . First of all, I'm so sorry for the delay replying here. We don't actively use this repo for development and notifications were not configured well so we just noticed your post. Did you manage to get a "Text to speech" solution working in UE?

**Comment by luis-valverde-ms** [comment]
Closing this as there has been no reply in a while. Please, do feel free to reopen.
