### ISSUE TITLE
Start Camera Capture causes application crash

### ISSUE THREAD

**Issue by nonlin** [microsoft/MixedRealityToolkit-Unreal#6]
To be clear I enable via "Set Enabled Mixed Reality Camera" the camera and set res via "Resize mixed reality camera" to 1920x1090 as shown here https://docs.microsoft.com/en-us/windows/mixed-reality/unreal-hololens-camera but calling the node "Start Camera Capture" causes application to crash and exit.

**Comment by Angelo-Gebauer** [comment]
Same here, we went as follows:
o	UE 4.25.3
o	UX Tools for Unreal v0.9.0
o	The HoloLens Plugin that ships with the engine
o	In our pawn we added a ARTrackableNotify Component, and called the static “StartCameraCapture” method from the HoloLensAR namespace in Blueprints
o	The capability for webcam is set

**Comment by AndreyChistyakov** [comment]
Please try to disable Multi-View in Project Parameters

**Comment by luis-valverde-ms** [comment]
@nonlin and @Angelo-Gebauer , is this still an issue for you?

**Comment by luis-valverde-ms** [comment]
Closing this as there has been no reply in a while, please feel free to re-open.
