### ISSUE TITLE
MRTK_Unreal for Linux??

### ISSUE THREAD

**Issue by ARtSSt** [microsoft/MixedRealityToolkit-Unreal#9]
Hello, is it possible to make the MRTK development package available for the UE4 Linux editors? 
I know Unity MRTK works in the official Unity Editor Linux builds for development, and then can be shared to win machines or Unity cloud builds for UWP deployment builds. 

Is it possible to make MRTK packages available for UE4 Linux?

**Comment by luis-valverde-ms** [comment]
@ARtSSt , very sorry for the late reply. We don't use this repo often and we didn't have notifications properly configured. Did you manage to build any of the MRTK-Unreal plugins for Linux? Is this still an issue for you?

**Comment by luis-valverde-ms** [comment]
Closing this as there has been no reply in a while, feel free to reopen. We don't support Linux at the moment because we rather focus our resources where most of our users are but would be happy to take any easy fixes to unblock that path.
